printWidth: 120
tabWidth: 2
useTabs: false
semi: false
singleQuote: true
quoteProps: 'as-needed'
trailingComma: 'none'
bracketSpacing: true
arrowParens: 'avoid'
requirePragma: false
insertPragma: false
proseWrap: 'preserve'
htmlWhitespaceSensitivity: 'css'
endOfLine: 'lf'
embeddedLanguageFormatting: 'auto'
singleAttributePerLine: false
